import Head from 'next/head';
import React from 'react';
import { Footer, Navbar } from '../components';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Coziestone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="bg-black">{children}</main>
      <Footer />
    </>
  );
};

export default Layout;
