import Head from 'next/head';
import React from 'react';
import { Footer, Navbar } from '../components';
import MobileNav from '../components/Navbar/MobileNav';
import ScrollTop from '../utils/ScrollTop';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Coziestone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileNav />
      <Navbar />
      <main className="bg-black">{children}</main>
      <ScrollTop />
      <Footer />
    </>
  );
};

export default Layout;
